package com.xiaoxiong.nbst01.mapper;

import com.xiaoxiong.nbst01.model.AccountInfo;
import com.xiaoxiong.nbst01.model.AccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    long countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_info (account_id, name, ",
        "birthday, sex, ",
        "portrait_url, address, ",
        "phone, email, ",
        "create_date)",
        "values (#{accountId,jdbcType=INTEGER}, #{name,jdbcType=LONGVARCHAR}, ",
        "#{birthday,jdbcType=LONGVARCHAR}, #{sex,jdbcType=LONGVARCHAR}, ",
        "#{portraitUrl,jdbcType=LONGVARCHAR}, #{address,jdbcType=LONGVARCHAR}, ",
        "#{phone,jdbcType=LONGVARCHAR}, #{email,jdbcType=LONGVARCHAR}, ",
        "#{createDate,jdbcType=LONGVARCHAR})"
    })
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    int insertSelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    List<AccountInfo> selectByExampleWithBLOBs(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);
}