server:
  port: 8402
  ssl:
      key-store: classpath:ssl/tomcat.keystore
      key-store-password: 123456
      trust-store:  classpath:ssl/ca.jks
      trust-store-type: JKS
      trust-store-password: Huawei@123
      key-alias: tomcat
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iotst?characterEncoding=utf8&useSSL=true
    username: root
    password: mysql123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.xiaoxiong.nbst01.model
    mapper-locations: classpath:mybatis/mapper/*.xml
nb:
  app:
    appId: bUdaovRg2LPofEI2ffob26djfFoa
    secret: BraEhVELcFSxrlNoYRfdDAkuKX4a
    serverIp: 180.101.147.89
    port: 8743
  device:
    deviceId: 0000
    name: ST08
    manufacturerId: xiaoxiong
    manufactureName: xiaoxiongguanjia
    deviceType: ST
    model: 01
    protocolType: CoAP

debug: true








